apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: no-image-pull-secret
  annotations:
    scenarios.ai.sap.com/description: "Behaviour testing"
    scenarios.ai.sap.com/name: "behaviour-testing"
    executables.ai.sap.com/description: "No image pull secret"
    executables.ai.sap.com/name: "no-image-pull-secret"
  labels:
    scenarios.ai.sap.com/id: "behaviour-testing"
    executables.ai.sap.com/id: "no-image-pull-secret"
spec:
  inputs:
    parameters:
      - default: 1
        name: minReplicas
        type: string
      - default: 2
        name: maxReplicas
        type: string
      - default: starter
        name: resourcePlan
        type: string
      - default: "eu.gcr.io/sap-ml-mlf-dev/com.sap.aicore/text-clf-serve:0.0.1"
        name: image
        type: string
    artifacts:
      - name: mymodel
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: {{inputs.parameters.resourcePlan}}
    spec: |
      predictor:
        minReplicas: {{inputs.parameters.minReplicas}}
        maxReplicas: {{inputs.parameters.maxReplicas}}
        containers:
          - name: kserve-container
            image: {{inputs.parameters.image}}
            ports:
              - containerPort: 9001
                protocol: TCP
            env:
              - name: STORAGE_URI
                value: "{{inputs.artifacts.mymodel}}"
